### ISSUE TITLE
ratted

### ISSUE THREAD

**Issue by JerryRune** [eagely/MeowMod#2]
So at first me and my friend were running some floor 6s for money. It started to get late so my friend got off and I continued playing. I got in a party with someone with a girl skin and a girly name. I friended her and asked if she was a girl, she said yes. After that run we partied and started running floor 6 together and we were having a lot of fun. We would message each other back and forth and I could tell we had an immediate bond. We both had similar humor and the same interests. After about an hour or two, I added her on discord and we took our chatting there. I was a bit hesitant to add her because what if it was a guy, that would be very upsetting. To my surprise, she asks to VC. I told her I had to go to the bathroom really quick, but I was really just sitting there mustering up the courage to talk to a girl. I joined the call and it astonishingly went well. We talked about our lives for over an hour. The conversation was going exceedingly well. Eventually, the conversation got back to skyblock. I asked her how she clears rooms remarkably fast and how she is so good at the game. She told me about a mod, that I will not name for the safety of readers, that helps immensely with dungeons. I stupidly downloaded the mod. A few minutes after I launched my game, she had to "go." I started a run with randoms, and mid-run, I get disconnected. The words "You logged in from another location!" displayed on my screen. I felt my fingertips go numb and my mind go blank. I opened discord and my heart sank. She blocked me. I scrambled to the Mojang website to reset my password, but it was too late. All 37 million coins were emptied from my bank account, my soul eater 3 rapid juju shortbow, my 3/4s fierce shadow assassin, everything. Everything was gone. I would always make fun of people getting hacked and ratted, but now it happened to me. The betray feels even worse than losing my profile.

**Comment by eagely** [comment]
sorry my bad will delete the mod
